---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wisdom.
--- DateTime: 2022/8/30 5:29 PM
---

-- 限流器

-- 用作限流的key
local limit_key = 'My Key'

-- 限流的时间窗口
local limit_time = 2

-- 当前流量大小
local current_limit = 0

-- 是否超出限流标准
if current_limit + 1 > limit_time then
    -- 超出限流标准
    -- 返回错误信息
    print("reject")
    return false
else
    -- 未超出限流标准
    -- 返回正常信息
    print('accept')
    return true
end